env: dev
log_level: trace
srv:
  network: tcp
  listen_address: :5041
  with_proxy: true
  with_reflection: true
db:
  driver: mysql
  database: test
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  max_idle_conns: 5
  max_open_conns: 10
  conn_max_lifetime: 3600